### ISSUE TITLE
User Face

### ISSUE THREAD

**Issue by MohaNoor** [bagussubagja/flutter-liveness-detection-randomized-plugin#3]
The app always gives me user face not found even if i follow the all instructions

**Comment by bagussubagja** [comment]
Thank you for bringing this issue to my attention. Here are a few things to check:

**Device Compatibility:**
Could you confirm the device model and operating system version you're using?

**Camera Permissions:**
Verify that the app has the required camera permissions. Sometimes, permission settings can block the app from accessing the camera.

Lastly, The face is clearly visible (not obstructed by glasses, masks, or hats)?

**Comment by MohaNoor** [comment]
Thanks for your response, my phone is onePlus 7 pro with android 12 and also I added the camera permission on manifest file

**Comment by MohaNoor** [comment]
Here's my WhatsApp number if you don't mind to contact with +971 503242703

**Comment by MohaNoor** [comment]
An i forgot to tell you when i download the source code from github and open it on android studio it's work

**Comment by bagussubagja** [comment]
thank you to confirm this package is working!
